### ISSUE TITLE
`AutoRestart()` doesn't work

### ISSUE THREAD

**Issue by alex-cherg** [mididings/mididings#11]
Hello,

I have the following simple `mididings` script:

```python
from mididings import *
from mididings.extra import *

from mididings.extra.inotify import AutoRestart


config(
    backend='jack',
)

hook(
    AutoRestart(),
)


def invert(ev):
    if ev.channel == 1:
        if ev.type == NOTEON:
            ev.velocity = 128 - ev.velocity
        return ev
    else:
        return None


run(Process(invert))
```

After running it with `python3 script.py` I get 

```bash
$ python3 script.py 
Traceback (most recent call last):
  File "/home/username/repos/audio/script.py", line 25, in <module>
    run(Process(invert))
  File "/home/username/.local/lib/python3.10/site-packages/mididings/overload.py", line 110, in call_overload
    return _registry[k](*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/mididings/overload.py", line 81, in __call__
    return call(args, kwargs, self.funcs, self.name)
  File "/home/username/.local/lib/python3.10/site-packages/mididings/overload.py", line 44, in call
    return f(*args, **kwargs)
  File "<decorator-gen-170>", line 2, in run
  File "/home/username/.local/lib/python3.10/site-packages/mididings/arguments.py", line 119, in wrapper
    return f(*mod_args, **mod_kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/mididings/engine.py", line 283, in run
    e.run()
  File "/home/username/.local/lib/python3.10/site-packages/mididings/engine.py", line 111, in run
    self._call_hooks('on_start')
  File "/home/username/.local/lib/python3.10/site-packages/mididings/engine.py", line 204, in _call_hooks
    f(*args)
  File "/home/username/.local/lib/python3.10/site-packages/mididings/extra/inotify.py", line 63, in on_start
    f = _os.path.abspath(m.__file__)
  File "/usr/lib/python3.10/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The script seems to run fine without the `AutoRestart()`. Ideally I would like to have the auto restarting functionality for quicker testing of `mididings` scripts. Could you please assist in resolving this?

**Comment by grawlinson** [comment]
`AutoRestart()` has a bunch of [parameters](https://mididings.github.io/mididings/extra.html#mididings.extra.inotify.AutoRestart) that you need to pass to it.

**Comment by alex-cherg** [comment]
According to the docs, the parameters are two (`AutoRestart(modules=True, filenames=[])`):
* `modules` – If true, all imported local Python modules are monitored for changes as well.
* `filenames` – a list of additional files to be monitored.
  
The script that I showed above was derived from an example script in the repo: https://github.com/mididings/mididings/blob/primary/doc/examples/skeleton.py, which has the commented out line:
``` python
hook(
    ...
    # mididings can automatically watch this script (and modules it imports)
    # for changes, and restart itself automatically
    #AutoRestart(),
)
```
So my understanding was that the default parameters `AutoRestart(modules=True, filenames=[])` should work outside of the box.

From my experience,
* `AutoRestart(modules=True, filenames=[])` leads to the error message initially reported above.
* `AutoRestart(modules=False, filenames=[])` allows the script to be started, but does not track the script for changes at all
* `AutoRestart(modules=False, filenames=['path/to/script.py'])` allows the script to be started and also tracks for changes, but once I change the script, I get the message `file 'path/to/script.py' changed, restarting...` and then I get two instances of the script visible in Carla and several seconds later Carla crashes

![mididings_two_scripts](https://user-images.githubusercontent.com/9079269/229934662-52a290d5-4a5a-4c1e-9d70-52aab9f5a204.png)
![mididings_carla_crash](https://user-images.githubusercontent.com/9079269/229934668-1a5a22c6-a10f-4708-aa99-3b4213d36007.png)

**Comment by stefets** [comment]
Hi guys, 

@alex-cherg, it look like you have 2 problems, the AutoRestart() and your jack connection.

If your AutoRestart works by specifying the filename, this is the expected behaviour and the Jack connection, must be disposed on shutdown and recreated at restart. AutoRestart() without parameters should works.

I use ALSA and I tried the AutoRestart() in my setup and it works without any parameters, no errors and my mididings script is fat as hell, meaning 12 input/output ports, 2000 lines of code and a bunch of plugins and the restart is lightning fast on my RPI-4.

My version is mididings 20230114, using Python 3.11.1

Can you try with the ALSA backend ?
Can you try with another hardware than the Carla device ?

**Comment by alex-cherg** [comment]
Hey @stefets , thanks for your input! The results above were with `backend='jack'` only. With `backend='alsa'` I get:
* `AutoRestart(modules=True, filenames=[])` Same error (check https://github.com/mididings/mididings/issues/11#issue-1652829457)
* `AutoRestart(modules=False, filenames=[])` allows the script to be started, but does not track the script for changes at all
* `AutoRestart(modules=False, filenames=['path/to/script.py'])` Successful restart :heavy_check_mark:

The only difference with `backend='jack'` is the success with `AutoRestart(modules=False, filenames=['path/to/script.py'])`.

The behaviour that is still unexpected is:
1. the error with default parameters (no matter what `backend` is)
2. the crash after restart with `AutoRestart(modules=False, filenames=['path/to/script.py'])` and `backend='jack'`

**Comment by stefets** [comment]
Hi  @alex-cherg, great that you have a workaround for the moment. 

What is your mididings version ?

**Comment by alex-cherg** [comment]
@stefets , this is my version:
```
mididings==20221230
Python 3.10.6
```

**Comment by stefets** [comment]
@alex-cherg, mine is 20230114.

Is a pip upgrade of mididings is an option for you ? Maybe there was a bug between releases ?
