### ISSUE TITLE
man pages in setup.py

### ISSUE THREAD

**Issue by rpmohn** [mididings/mididings#13]
When I run `python ./setup.py build` it doesn't do anything with the `doc/man/*.scd` files, and then when I run `python ./setup.py  install` it gives the error `error: can't copy 'doc/man/mididings.1': doesn't exist or not a regular file`. Is the intention that I pre-build those files using something like `for x in *.scd; do scdoc < $x > ${x%%.scd}.1; done` and then `bash ./reproducible-man.sh`?

I've run those pre-build commands and gotten a clean installation, but that puts the three man pages under `lib/python3.8/site-packages/mididings-20230114-py3.8-linux-x86_64.egg/share/man/man1/`, which isn't found in my `MANPATH`, so I've manually copied them to a location that is. 

I suppose my overall question is, what is the intention with these man pages. Thanks! -Ross

**Comment by rpmohn** [comment]
Ah, I'm just seeing that I should use `just` to build rather than manully running the `setup.py` script. I've downloaded the pre-built version, grabbed a fresh clone of mididings, and now I get this error:
```
$ just build
python3 -m build --no-isolation --wheel
/usr/bin/python3: No module named build
error: Recipe `build-wheel` failed on line 37 with exit code 1
```

**Comment by stefets** [comment]
Hi, You have to *pip install build* I think

**Comment by rpmohn** [comment]
> Hi, You have to _pip install build_ I think

Yes, that worked, thank you!
