### ISSUE TITLE
Allow the edition of the mididings's Wiki

### ISSUE THREAD

**Issue by stefets** [mididings/mididings#14]
It would be appreciated, if possible, to authorize the edition of the Wiki in order to share our knowledge. 

The dsacre/mididings wiki is editable unlike your community version wiki and I would like to add a link to procedures from my Wiki which *explains step by step how to build mididings latest version* 

This procedure can help users to upgrade from outdated version or help less experienced users.

It's also important for future users, I want to prevent them from giving up with simple and up-to-date procedures.

In addition, users can validate and add elements in procedures.

I'm at this level for now https://github.com/stefets/live-config/wiki

Thanks

**Comment by grawlinson** [comment]
Agreed, I’ll fiddle with the settings after work. :)

edit: can you give that a go now?

**Comment by stefets** [comment]
> edit: can you give that a go now?

@grawlinson It looks fine :+1:  the Edit button is available

Thanks !
