### ISSUE TITLE
Duplicate name in TOC

### ISSUE THREAD

**Issue by stefets** [mididings/mididings#9]
This low impact issue concerns the new documentation site https://mididings.github.io/mididings/

It's very usefull to have a more detail TOC but there are duplicate names in the TOC.

For instance : 
* KeyFilter()
* KeyFilterKeyFilter()
* VelocityFilter()
* VelocityFilterVelocityFilter()
* CtrlValueFilter()
* CtrlValueFilterCtrlValueFilter()
* etc...

Thanks!

**Comment by grawlinson** [comment]
Yeah, I was wondering about that myself ... It looks like sphinx is picking up function overrides and just shoving them all into similar headings.

**Comment by grawlinson** [comment]
references for later perusal:

* [sphinx-toolbox](https://sphinx-toolbox.readthedocs.io/en/latest/extensions/more_autodoc/overloads.html) more_autodoc.overloads extension
* [upstream sphinx issue](https://github.com/sphinx-doc/sphinx/issues/7787)

**Comment by grawlinson** [comment]
You'll be happy to see the updated documentation! :)

**Comment by stefets** [comment]
> You'll be happy to see the updated documentation! :)

Indeed!  Big thanks!
